src/java/Controller/RoomController.java
package Controller;

import Entity.Room;
import Controller.util.JsfUtil;
import Controller.util.PaginationHelper;
import Entity.FeatureRoom;
import Entity.Hotel;
import Model.FeatureRoomFacade;
import Model.RoomFacade;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;
import javax.inject.Inject;
import javax.servlet.ServletContext;
import org.primefaces.event.CellEditEvent;
import org.primefaces.event.FileUploadEvent;
import org.primefaces.event.RowEditEvent;

@Named("roomController")
@SessionScoped
public class RoomController implements Serializable {

    private Room current;
    private List<Room> rooms;
    private DataModel items = null;
    @EJB
    private Model.RoomFacade ejbFacade;
    @Inject
    private HotelController hotelController;
    @EJB
    private Model.FeatureRoomFacade ejbRFFacade;
    private FeatureRoom [] features;
    private PaginationHelper pagination;
    private int selectedItemIndex;
    
    //Amar added for pictures
    private File file;
    private final String path = "resources" + File.separator + "uploadroom";
    private final ServletContext servletContext = (ServletContext) FacesContext.getCurrentInstance().getExternalContext().getContext();
    private String destination = servletContext.getRealPath(File.separator + path);

    public RoomController() {
    }

    public HotelController getHotelController() {
        return hotelController;
    }

//    @PostConstruct
//    public void setInit(){
//        rooms= hotelController.getRooms();
//    }

    public List<Room> getRooms() {
        return rooms;
    }
    
    public Room getSelected() {
        if (current == null) {
            current = new Room();
            selectedItemIndex = -1;
        }
        return current;
    }

    private RoomFacade getFacade() {
        return ejbFacade;
    }
 public FeatureRoom[] getFeatures() {
        return features;
    }

    public void setFeatures(FeatureRoom[] features) {
        this.features = features;
    }

    public FeatureRoomFacade getEjbRFFacade() {
        return ejbRFFacade;
    }

    
    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Room) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Room();
        selectedItemIndex = -1;
        return "Create";
    }

        public void addFeature(){
        if(features.length>0){
        for(FeatureRoom f: features){
            current.getFeatureRooms().add(f);
            f.getRooms().add(current);
        }
        }
    }
    private void editFearure() {
        for(FeatureRoom f: current.getFeatureRooms()){
            getEjbRFFacade().edit(f);
        }
    }
    
    public String create() {
        try {
            if (file.getName() != null) {
                current.setPath(path + File.separator + file.getName());
            }
            getFacade().create(current);
            addFeature();
            getFacade().edit(current);
            editFearure();
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("RoomCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Room) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("RoomUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Room) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("RoomDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public Room getRoom(java.lang.Long id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = Room.class)
    public static class RoomControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            RoomController controller = (RoomController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "roomController");
            return controller.getRoom(getKey(value));
        }

        java.lang.Long getKey(String value) {
            java.lang.Long key;
            key = Long.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Long value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Room) {
                Room o = (Room) object;
                return getStringKey(o.getId());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Room.class.getName());
            }
        }

    }
    
    public void upload(FileUploadEvent event) {
        FacesMessage msg = new FacesMessage("Success! ", event.getFile().getFileName() + " is uploaded.");
        FacesContext.getCurrentInstance().addMessage(null, msg);
        try {
            copyFile(event.getFile().getFileName(), event.getFile().getInputstream());
        } catch (IOException e) {
            System.out.println(e.getMessage());
        }
    }


web/room/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateRoomTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreateRoomLabel_id}" for="id" />
                    <h:inputText id="id" value="#{roomController.selected.id}" title="#{bundle.CreateRoomTitle_id}" />
                    <h:outputLabel value="#{bundle.CreateRoomLabel_hotel}" for="hotel" />
                    <h:selectOneMenu id="hotel" value="#{roomController.selected.hotel}" title="#{bundle.CreateRoomTitle_hotel}" >
                        <f:selectItems value="#{hotelController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="#{bundle.CreateRoomLabel_type}" for="type" />
                    <h:inputText id="type" value="#{roomController.selected.type}" title="#{bundle.CreateRoomTitle_type}" />
                    <h:outputLabel value="#{bundle.CreateRoomLabel_smoking}" for="smoking" />
                    <h:inputText id="smoking" value="#{roomController.selected.smoking}" title="#{bundle.CreateRoomTitle_smoking}" />
                    <h:outputLabel value="#{bundle.CreateRoomLabel_price}" for="price" />
                    <h:inputText id="price" value="#{roomController.selected.price}" title="#{bundle.CreateRoomTitle_price}" />
                    <h:outputLabel value="Photo" for="photo" />
                    <p:fileUpload fileUploadListener="#{roomController.upload}" mode="advanced" dragDropSupport="true"
                            multiple="true" update="messages" sizeLimit="1000000" fileLimit="10" allowTypes="/(\.|\/)(gif|jpe?g|png)$/" />
                    <p:growl id="messages" showDetail="true" />
                </h:panelGrid>
                <br/>
                <p:dataTable value="#{featureRoomController.items}" var="feature" tableStyle="width:auto"
                             selection="#{roomController.features}"  rowKey='#{feature}'>
                   <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListFeatureHotelTitle_feature_type}"/>
                            </f:facet>
                            <h:outputText value="#{feature.feature_type}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListFeatureHotelTitle_discription}"/>
                            </f:facet>
                            <h:outputText value="#{feature.discription}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListFeatureHotelTitle_id}"/>
                            </f:facet>
                            <h:outputText value="#{feature.id}"/>
                        </p:column>
                    
                    <p:column selectionMode="multiple" style="width:2%" />
                </p:dataTable>
                <br />
                <h:commandLink action="#{roomController.create}" value="#{bundle.CreateRoomSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{roomController.prepareList}" value="#{bundle.CreateRoomShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.CreateRoomIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/room/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditRoomTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditRoomLabel_id}" for="id" />
                    <h:inputText id="id" value="#{roomController.selected.id}" title="#{bundle.EditRoomTitle_id}" />
                    <h:outputLabel value="#{bundle.EditRoomLabel_hotel}" for="hotel" />
                    <h:selectOneMenu id="hotel" value="#{roomController.selected.hotel}" title="#{bundle.EditRoomTitle_hotel}" >
                        <f:selectItems value="#{hotelController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="#{bundle.EditRoomLabel_type}" for="type" />
                    <h:inputText id="type" value="#{roomController.selected.type}" title="#{bundle.EditRoomTitle_type}" />
                    <h:outputLabel value="#{bundle.EditRoomLabel_smoking}" for="smoking" />
                    <h:inputText id="smoking" value="#{roomController.selected.smoking}" title="#{bundle.EditRoomTitle_smoking}" />
                    <h:outputLabel value="#{bundle.EditRoomLabel_price}" for="price" />
                    <h:inputText id="price" value="#{roomController.selected.price}" title="#{bundle.EditRoomTitle_price}" />
                </h:panelGrid>
                
                
                                    <h:graphicImage value="../#{roomController.selected.path}" width="160" />
                                <h:graphicImage value="../resources/images/default_product.png" width="160" rendered="#{empty roomController.selected.path}" /><br/><br/>
                <h:commandLink action="#{roomController.update}" value="#{bundle.EditRoomSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditRoomViewLink}"/>
                <br />
                <h:commandLink action="#{roomController.prepareList}" value="#{bundle.EditRoomShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditRoomIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/room/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListRoomTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form id="form" styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListRoomEmpty}" rendered="#{roomController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{roomController.items.rowCount > 0}">
                    <h:outputText value="#{roomController.pagination.pageFirstItem + 1}..#{roomController.pagination.pageLastItem + 1}/#{roomController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{roomController.previous}" value="#{bundle.Previous} #{roomController.pagination.pageSize}" rendered="#{roomController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{roomController.next}" value="#{bundle.Next} #{roomController.pagination.pageSize}" rendered="#{roomController.pagination.hasNextPage}"/>&nbsp;
                    <p:growl id="msgs" showDetail="true"/>
                    <p:dataTable value="#{roomController.items}" var="item" editable="true" style="margin-bottom:20px">
                        <f:facet name="header">
                            Rooms
                        </f:facet>
                        <p:ajax event="rowEdit" listener="#{roomController.onRowEdit}" update=":form:msgs" />
                        <p:ajax event="rowEditCancel" listener="#{roomController.onRowCancel}" update=":form:msgs" />
 
                        <p:column headerText="ID" style="width:64px">
                            <p:cellEditor>
                            <f:facet name="output"><h:outputText value="#{item.id}"/></f:facet>
                            <f:facet name="input"><h:inputText value="#{item.id}"/></f:facet>
                            </p:cellEditor>
                        </p:column>
                         <p:column headerText="Type" style="width:120px">
                            <p:cellEditor>
                            <f:facet name="output"><h:outputText value="#{item.type}"/></f:facet>
                            <f:facet name="input"><h:inputText value="#{item.type}"/></f:facet>
                            </p:cellEditor>
                        </p:column>
                        <p:column headerText="Price" style="width:64px">
                            <p:cellEditor>
                                <f:facet name="output"><h:outputText value="#{item.price}"/></f:facet>
                                <f:facet name="input"><h:inputText value="#{item.price}"/></f:facet>
                            </p:cellEditor>
                        </p:column>
                        <p:column headerText="Smooking" style="width:120px">
                            <p:cellEditor>
                                <f:facet name="output"> <h:outputText value="#{item.smoking}"/></f:facet>
                                <f:facet name="input"> <h:inputText value="#{item.smoking}"/></f:facet>
                            </p:cellEditor>
                        </p:column>
                        <p:column headerText="Hotel" style="width:100px">
                            <p:cellEditor>
                                <f:facet name="output"><h:outputText value="#{item.hotel}"/></f:facet>
                                <f:facet name="input">
                                    <h:selectOneMenu value="#{item.hotel}" style="width:100%">
                                        <f:selectItems value="#{hotelController.itemsAvailableSelectOne}" var="color" itemLabel="#{color}" itemValue="#{color}" />
                                    </h:selectOneMenu>
                                </f:facet>
                            </p:cellEditor>
                        </p:column>
                                              
                        <p:column style="width:32px">
                            <p:rowEditor />
                        </p:column>
                         <p:column style="width:60px">
                            
                            <p:commandButton icon="ui-icon-close"
                                             title="Delete this hotel"
                                             actionListener="#{roomController.destroy}"
                                             ajax="false" />
                        </p:column>
                    </p:dataTable>
                </h:panelGroup>
                
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/room/ListOfRooms.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListRoomTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListRoomEmpty}" rendered="#{roomController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{roomBookingController.rooms.size() > 0}">
                    <h:outputText value="#{roomController.pagination.pageFirstItem + 1}..#{roomController.pagination.pageLastItem + 1}/#{roomController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{roomController.previous}" value="#{bundle.Previous} #{roomController.pagination.pageSize}" rendered="#{roomController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{roomController.next}" value="#{bundle.Next} #{roomController.pagination.pageSize}" rendered="#{roomController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{roomBookingController.rooms}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListRoomTitle_id}"/>
                            </f:facet>
                            <h:outputText value="#{item.id}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListRoomTitle_hotel}"/>
                            </f:facet>
                            <h:outputText value="#{item.hotel}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListRoomTitle_type}"/>
                            </f:facet>
                            <h:outputText value="#{item.type}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListRoomTitle_smoking}"/>
                            </f:facet>
                            <h:outputText value="#{item.smoking}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListRoomTitle_price}"/>
                            </f:facet>
                            <h:outputText value="#{item.price}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandButton action="#{roomBookingController.addingRoom(item)}" value="Select"/>
                            
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{roomController.prepareCreate}" value="#{bundle.ListRoomCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ListRoomIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/room/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewRoomTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewRoomLabel_id}"/>
                    <h:outputText value="#{roomController.selected.id}" title="#{bundle.ViewRoomTitle_id}"/>
                    <h:outputText value="#{bundle.ViewRoomLabel_hotel}"/>
                    <h:outputText value="#{roomController.selected.hotel}" title="#{bundle.ViewRoomTitle_hotel}"/>
                    <h:outputText value="#{bundle.ViewRoomLabel_type}"/>
                    <h:outputText value="#{roomController.selected.type}" title="#{bundle.ViewRoomTitle_type}"/>
                    <h:outputText value="#{bundle.ViewRoomLabel_smoking}"/>
                    <h:outputText value="#{roomController.selected.smoking}" title="#{bundle.ViewRoomTitle_smoking}"/>
                    <h:outputText value="#{bundle.ViewRoomLabel_price}"/>
                    <h:outputText value="#{roomController.selected.price}" title="#{bundle.ViewRoomTitle_price}"/>
                </h:panelGrid>
                <br />
                                    <h:graphicImage value="../#{roomController.selected.path}" width="160" />
                                <h:graphicImage value="../resources/images/default_product.png" width="160" rendered="#{empty roomController.selected.path}" /><br/><br/>
                <h:commandLink action="#{roomController.destroyAndView}" value="#{bundle.ViewRoomDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{bundle.ViewRoomEditLink}"/>
                <br />
                <h:commandLink action="#{roomController.prepareCreate}" value="#{bundle.ViewRoomCreateLink}" />
                <br />
                <h:commandLink action="#{roomController.prepareList}" value="#{bundle.ViewRoomShowAllLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ViewRoomIndexLink}"/>

            </h:form>
        </ui:define>
    </ui:composition>

</html>