src/java/Controller/AdministratorController.java
package Controller;

import Entity.Administrator;
import Controller.util.JsfUtil;
import Controller.util.PaginationHelper;
import Model.AdministratorFacade;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@Named("administratorController")
@SessionScoped
public class AdministratorController implements Serializable {

    private Administrator current;
    private DataModel items = null;
    @EJB
    private Model.AdministratorFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public AdministratorController() {
    }

    public Administrator getSelected() {
        if (current == null) {
            current = new Administrator();
            selectedItemIndex = -1;
        }
        return current;
    }

    private AdministratorFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Administrator) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Administrator();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("AdministratorCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Administrator) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("AdministratorUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Administrator) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("AdministratorDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public Administrator getAdministrator(java.lang.Long id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = Administrator.class)
    public static class AdministratorControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            AdministratorController controller = (AdministratorController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "administratorController");
            return controller.getAdministrator(getKey(value));
        }

        java.lang.Long getKey(String value) {
            java.lang.Long key;
            key = Long.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Long value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Administrator) {
                Administrator o = (Administrator) object;
                return getStringKey(o.getId());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Administrator.class.getName());
            }
        }

    }

}

web/administrator/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateAdministratorTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="1">
                    <p:inputText id="fname" value="#{administratorController.selected.fname}" placeholder="First name" />
                    <p:inputText id="lname" value="#{administratorController.selected.lname}" placeholder="Last name" />
                    <p:password id="password" value="#{administratorController.selected.password}" placeholder="Password" />
                    <p:inputText id="email" value="#{administratorController.selected.email}" placeholder="Email" size="32"/>
                    <p:inputText id="street" value="#{administratorController.selected.address.street}" placeholder="Street" size="32"/>
                    <p:inputText id="city" value="#{administratorController.selected.address.city}" placeholder="City" />
                    <p:inputText id="state" value="#{administratorController.selected.address.province}" placeholder="State" />
                    <p:inputText id="zipCode" value="#{administratorController.selected.address.zipCode}" placeholder="Zip" />
                    <p:inputText id="phone" value="#{administratorController.selected.address.phone}" placeholder="Phone" />

                </h:panelGrid>
                <br />
                <h:commandLink action="#{administratorController.create}" value="#{bundle.CreateAdministratorSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{administratorController.prepareList}" value="#{bundle.CreateAdministratorShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.CreateAdministratorIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/administrator/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditAdministratorTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditAdministratorLabel_id}" for="id" />
                    <h:inputText id="id" value="#{administratorController.selected.id}" title="#{bundle.EditAdministratorTitle_id}" />
                    <h:outputLabel value="#{bundle.EditAdministratorLabel_address}" for="address" />
                    <h:inputText id="address" value="#{administratorController.selected.address}" title="#{bundle.EditAdministratorTitle_address}" />
                    <h:outputLabel value="#{bundle.EditAdministratorLabel_fname}" for="fname" />
                    <h:inputText id="fname" value="#{administratorController.selected.fname}" title="#{bundle.EditAdministratorTitle_fname}" />
                    <h:outputLabel value="#{bundle.EditAdministratorLabel_lname}" for="lname" />
                    <h:inputText id="lname" value="#{administratorController.selected.lname}" title="#{bundle.EditAdministratorTitle_lname}" />
                    <h:outputLabel value="#{bundle.EditAdministratorLabel_email}" for="email" />
                    <h:inputText id="email" value="#{administratorController.selected.email}" title="#{bundle.EditAdministratorTitle_email}" />
                    <h:outputLabel value="#{bundle.EditAdministratorLabel_password}" for="password" />
                    <h:inputText id="password" value="#{administratorController.selected.password}" title="#{bundle.EditAdministratorTitle_password}" />
                </h:panelGrid>
                <h:commandLink action="#{administratorController.update}" value="#{bundle.EditAdministratorSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditAdministratorViewLink}"/>
                <br />
                <h:commandLink action="#{administratorController.prepareList}" value="#{bundle.EditAdministratorShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditAdministratorIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/administrator/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListAdministratorTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form id="form" styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListAdministratorEmpty}" rendered="#{administratorController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{administratorController.items.rowCount > 0}">
                    <h:outputText value="#{administratorController.pagination.pageFirstItem + 1}..#{administratorController.pagination.pageLastItem + 1}/#{administratorController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{administratorController.previous}" value="#{bundle.Previous} #{administratorController.pagination.pageSize}" rendered="#{administratorController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{administratorController.next}" value="#{bundle.Next} #{administratorController.pagination.pageSize}" rendered="#{administratorController.pagination.hasNextPage}"/>&nbsp;
                    <p:growl id="msgs" showDetail="true"/>
                    <p:dataTable value="#{administratorController.items}" var="item" editable="true" style="margin-bottom:20px">
                        <f:facet name="header">
                            Admin
                        </f:facet>
                        <p:ajax event="rowEdit" listener="#{accountController.onRowEdit}" update=":form:msgs" />
                        <p:ajax event="rowEditCancel" listener="#{accountController.onRowCancel}" update=":form:msgs" />
 
                       <p:column headerText="ID">
                            <p:cellEditor>
                            <f:facet name="output"><h:outputText value="#{item.id}"/></f:facet>
                            <f:facet name="input"><h:inputText value="#{item.id}"/></f:facet>
                            </p:cellEditor>
                        </p:column>
                        <p:column headerText="First Name">
                            <p:cellEditor>
                            <f:facet name="output"><h:outputText value="#{item.fname}"/></f:facet>
                            <f:facet name="input"><h:inputText value="#{item.fname}"/></f:facet>
                            </p:cellEditor>
                        </p:column>
                        <p:column headerText="Last Name">
                            <p:cellEditor>
                            <f:facet name="output"><h:outputText value="#{item.lname}"/></f:facet>
                            <f:facet name="input"><h:inputText value="#{item.lname}"/></f:facet>
                            </p:cellEditor>
                        </p:column>
                        <p:column headerText="Email">
                            <p:cellEditor>
                            <f:facet name="output"><h:outputText value="#{item.email}"/></f:facet>
                            <f:facet name="input"><h:inputText value="#{item.email}"/></f:facet>
                            </p:cellEditor>
                        </p:column>
                        <p:column headerText="Street">
                            <p:cellEditor>
                                <f:facet name="output"><h:outputText value="#{item.address.street}"/></f:facet>
                                <f:facet name="input"><h:inputText value="#{item.address.street}"/></f:facet>
                            </p:cellEditor>
                        </p:column>
                        <p:column headerText="City" style="width:100px">
                            <p:cellEditor>
                                <f:facet name="output"> <h:outputText value="#{item.address.city}"/></f:facet>
                                <f:facet name="input"> <h:inputText value="#{item.address.city}"/></f:facet>
                            </p:cellEditor>
                        </p:column>
                        <p:column headerText="State" style="width:100px">
                            <p:cellEditor>
                                <f:facet name="output"><h:outputText value="#{item.address.province}"/></f:facet>
                                <f:facet name="input"><h:inputText value="#{item.address.province}"/></f:facet>
                            </p:cellEditor>
                        </p:column>
                        <p:column headerText="Zip" style="width:80px">
                            <p:cellEditor>
                            <f:facet name="output"><h:outputText value="#{item.address.zipCode}"/></f:facet>
                            <f:facet name="input"><h:inputText value="#{item.address.zipCode}"/></f:facet>
                            </p:cellEditor>
                        </p:column>
                        <p:column headerText="Phone">
                            <p:cellEditor>
                            <f:facet name="output"><h:outputText value="#{item.address.phone}"/></f:facet>
                            <f:facet name="input"><h:inputText value="#{item.address.phone}"/></f:facet>
                            </p:cellEditor>
                        </p:column>
                        <p:column>
                            <p:column style="width:30px">
                                <p:rowEditor />
                            </p:column>
                        </p:column>
                         <p:column style="width:60px">
                            
                            <p:commandButton icon="ui-icon-close"
                                             title="Delete this hotel"
                                             actionListener="#{accountController.destroy}"
                                             ajax="false" />
                        </p:column>
                    </p:dataTable>
                </h:panelGroup>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/administrator/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewAdministratorTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewAdministratorLabel_id}"/>
                    <h:outputText value="#{administratorController.selected.id}" title="#{bundle.ViewAdministratorTitle_id}"/>
                    <h:outputText value="#{bundle.ViewAdministratorLabel_address}"/>
                    <h:outputText value="#{administratorController.selected.address}" title="#{bundle.ViewAdministratorTitle_address}"/>
                    <h:outputText value="#{bundle.ViewAdministratorLabel_fname}"/>
                    <h:outputText value="#{administratorController.selected.fname}" title="#{bundle.ViewAdministratorTitle_fname}"/>
                    <h:outputText value="#{bundle.ViewAdministratorLabel_lname}"/>
                    <h:outputText value="#{administratorController.selected.lname}" title="#{bundle.ViewAdministratorTitle_lname}"/>
                    <h:outputText value="#{bundle.ViewAdministratorLabel_email}"/>
                    <h:outputText value="#{administratorController.selected.email}" title="#{bundle.ViewAdministratorTitle_email}"/>
                    <h:outputText value="#{bundle.ViewAdministratorLabel_password}"/>
                    <h:outputText value="#{administratorController.selected.password}" title="#{bundle.ViewAdministratorTitle_password}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{administratorController.destroyAndView}" value="#{bundle.ViewAdministratorDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{bundle.ViewAdministratorEditLink}"/>
                <br />
                <h:commandLink action="#{administratorController.prepareCreate}" value="#{bundle.ViewAdministratorCreateLink}" />
                <br />
                <h:commandLink action="#{administratorController.prepareList}" value="#{bundle.ViewAdministratorShowAllLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ViewAdministratorIndexLink}"/>

            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/administrator/adminHome.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateHotelTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">     
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreateHotelLabel_id}" for="id" />
                    <h:inputText id="id" value="#{hotelController.selected.id}" title="#{bundle.CreateHotelTitle_id}" />
                    <h:outputLabel value="#{bundle.CreateHotelLabel_name}" for="name" />
                    <h:inputText id="name" value="#{hotelController.selected.name}" title="#{bundle.CreateHotelTitle_name}" />
                    <h:outputLabel value="Street" for="street" />
                    <h:inputText id="street" value="#{hotelController.address.street}" title="Street" />
                    <h:outputLabel value="City" for="city" />
                    <h:inputText id="city" value="#{hotelController.address.city}" title="City" />
                    <h:outputLabel value="State" for="state" />
                    <h:inputText id="state" value="#{hotelController.address.province}" title="State" />
                    <h:outputLabel value="Zip Code" for="zipCode" />
                    <h:inputText id="zipCode" value="#{hotelController.address.zipCode}" title="Zip Code" />
                    <h:outputLabel value="Phone" for="phone" />
                    <h:inputText id="phone" value="#{hotelController.address.phone}" title="Phone" />
                    <h:outputLabel value="Photos" for="photos" />
                    <p:fileUpload fileUploadListener="#{hotelController.upload}" mode="advanced" dragDropSupport="true"
                            multiple="true" update="messages" sizeLimit="1000000" fileLimit="10" allowTypes="/(\.|\/)(gif|jpe?g|png)$/" />
                    <p:growl id="messages" showDetail="true" />
                </h:panelGrid>
                <br/>
                <p:dataTable value="#{featureHotelController.items}" var="feature" tableStyle="width:auto"
                             selection="#{hotelController.features}"  rowKey='#{feature}'>
                   <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListFeatureHotelTitle_feature_type}"/>
                            </f:facet>
                            <h:outputText value="#{feature.feature_type}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListFeatureHotelTitle_discription}"/>
                            </f:facet>
                            <h:outputText value="#{feature.discription}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListFeatureHotelTitle_id}"/>
                            </f:facet>
                            <h:outputText value="#{feature.id}"/>
                        </p:column>
                    
                    <p:column selectionMode="multiple" style="width:2%" />
                </p:dataTable>
<!--                <h:selectManyCheckbox id="grid" value="#{hotelController.features}" layout="grid" >
                    <f:selectItems value="#{featureHotelController.itemsAvailableSelectMany}" var="feature" itemLabel="#{feature}" itemValue="#{feature.description}" />

                </h:selectManyCheckbox>-->
                <h:commandLink action="#{hotelController.create}" value="#{bundle.CreateHotelSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{hotelController.prepareList}" value="#{bundle.CreateHotelShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.CreateHotelIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>